import type { GeoContent } from '../types';
import { StarMap, type StarNode } from '../maps';

const starNodes: StarNode[] = [
  { id: 'alpha-station', x: 0.2, y: 0.2 },
  { id: 'rift-observatory', x: 0.45, y: 0.2 },
  { id: 'nebula-lab', x: 0.68, y: 0.18 },
  { id: 'warp-gate', x: 0.55, y: 0.32 },
  { id: 'quantum-beacon', x: 0.3, y: 0.4 },
  { id: 'crystal-planet', x: 0.38, y: 0.58 },
  { id: 'void-relay', x: 0.18, y: 0.6 },
  { id: 'aurora-outpost', x: 0.72, y: 0.58 },
  { id: 'dyson-ring', x: 0.82, y: 0.4 },
  { id: 'eclipse-harbor', x: 0.5, y: 0.75 },
  { id: 'comet-forge', x: 0.63, y: 0.78 },
  { id: 'lumen-reef', x: 0.83, y: 0.74 },
];

export const futuristicContent: GeoContent = {
  id: 'futuristic',
  name: 'Star Navigator',
  quest: 'Chart the luminous network of star systems and anomaly hubs.',
  rounds: 10,
  mapBackground:
    'radial-gradient(circle at 20% 20%, rgba(0,229,255,0.18), transparent 40%), radial-gradient(circle at 80% 30%, rgba(224,64,251,0.18), transparent 45%), linear-gradient(180deg, #0b0e1a 0%, #12162b 100%)',
  map: <StarMap nodes={starNodes} />,
  locations: [
    {
      id: 'alpha-station',
      name: 'Alpha Station',
      x: 0.2,
      y: 0.2,
      description: 'A bustling trade hub where long-haul pilots refuel and exchange data.',
      funFact: 'Alpha Station is famous for its zero-g market plaza.',
    },
    {
      id: 'rift-observatory',
      name: 'Rift Observatory',
      x: 0.45,
      y: 0.2,
      description: 'Astronomers track spacetime fractures from this shimmering platform.',
      funFact: 'The observatory can predict warp storms three cycles ahead.',
    },
    {
      id: 'nebula-lab',
      name: 'Nebula Research Lab',
      x: 0.68,
      y: 0.18,
      description: 'A drifting laboratory tucked inside a glowing gas cloud.',
      funFact: 'Its sensors map particle winds in real time.',
    },
    {
      id: 'warp-gate',
      name: 'Warp Gate Nexus',
      x: 0.55,
      y: 0.32,
      description: 'The central relay that stitches distant systems into one network.',
      funFact: 'The gate can spin up in under 90 seconds.',
    },
    {
      id: 'quantum-beacon',
      name: 'Quantum Beacon',
      x: 0.3,
      y: 0.4,
      description: 'A signal tower that broadcasts encrypted guidance across the void.',
      funFact: 'Pilots rely on its pulse to sync interstellar navigation.',
    },
    {
      id: 'crystal-planet',
      name: 'Crystal Planet',
      x: 0.38,
      y: 0.58,
      description: 'A world of refractive spires that bend light into auroras.',
      funFact: 'Mining here powers half the grid’s shields.',
    },
    {
      id: 'void-relay',
      name: 'Void Relay',
      x: 0.18,
      y: 0.6,
      description: 'A silent outpost sending deep-space telemetry homeward.',
      funFact: 'The relay’s antenna array spans two kilometers.',
    },
    {
      id: 'aurora-outpost',
      name: 'Aurora Outpost',
      x: 0.72,
      y: 0.58,
      description: 'Scientific habitat orbiting a vibrant magnetized planet.',
      funFact: 'Its shields shimmer with constant aurora activity.',
    },
    {
      id: 'dyson-ring',
      name: 'Dyson Ring',
      x: 0.82,
      y: 0.4,
      description: 'An incomplete megastructure harvesting stellar energy.',
      funFact: 'The ring segments rotate to balance gravity tides.',
    },
    {
      id: 'eclipse-harbor',
      name: 'Eclipse Harbor',
      x: 0.5,
      y: 0.75,
      description: 'A cargo haven hidden in the shadow of twin moons.',
      funFact: 'Harbor lights only flare during scheduled convoys.',
    },
    {
      id: 'comet-forge',
      name: 'Comet Forge',
      x: 0.63,
      y: 0.78,
      description: 'A refinery that captures icy comets for propulsion fuel.',
      funFact: 'Its forges blaze with pale blue plasma.',
    },
    {
      id: 'lumen-reef',
      name: 'Lumen Reef',
      x: 0.83,
      y: 0.74,
      description: 'Bioluminescent nebula clusters that glow like underwater reefs.',
      funFact: 'Navigators use the glow to chart gravity eddies.',
    },
  ],
};
