import type { GeoContent } from '../types';
import { WorldMap } from '../maps';

export const organicContent: GeoContent = {
  id: 'organic',
  name: 'Wild Atlas',
  quest: 'Trace rare ecosystems and natural wonders across the living world.',
  rounds: 10,
  mapBackground:
    'linear-gradient(180deg, #f5f0e8 0%, #e7dccb 100%)',
  map: <WorldMap variant="organic" />,
  locations: [
    {
      id: 'great-barrier-reef',
      name: 'Great Barrier Reef',
      x: 0.85,
      y: 0.76,
      description: 'A vibrant coral network visible from orbit, alive with marine color.',
      funFact: 'It is the largest coral reef system on Earth.',
    },
    {
      id: 'amazon-rainforest',
      name: 'Amazon Rainforest',
      x: 0.3,
      y: 0.62,
      description: 'An enormous canopy biome storing some of the planet’s richest biodiversity.',
      funFact: 'The Amazon spans nine countries.',
    },
    {
      id: 'galapagos',
      name: 'Galápagos Islands',
      x: 0.24,
      y: 0.6,
      description: 'Volcanic islands famous for species found nowhere else on Earth.',
      funFact: 'They helped inspire Darwin’s theory of evolution.',
    },
    {
      id: 'serengeti',
      name: 'Serengeti',
      x: 0.55,
      y: 0.56,
      description: 'Rolling grasslands known for the great migration of wildebeest and zebra.',
      funFact: 'Over a million wildebeest travel here each year.',
    },
    {
      id: 'dead-sea',
      name: 'Dead Sea',
      x: 0.6,
      y: 0.44,
      description: 'A mineral-rich lake where the water is so salty you can float effortlessly.',
      funFact: 'It is one of the saltiest bodies of water on Earth.',
    },
    {
      id: 'northern-lights',
      name: 'Northern Lights (Iceland)',
      x: 0.45,
      y: 0.16,
      description: 'Auroral ribbons ripple across the night sky in emerald hues.',
      funFact: 'The lights are caused by charged solar particles.',
    },
    {
      id: 'redwood-forest',
      name: 'Redwood Forest',
      x: 0.18,
      y: 0.32,
      description: 'Ancient towering trees create a cathedral of green on the coast.',
      funFact: 'Some redwoods are over 2,000 years old.',
    },
    {
      id: 'zhangjiajie',
      name: 'Zhangjiajie Pillars',
      x: 0.75,
      y: 0.42,
      description: 'Misty stone spires inspired the floating mountains of science fiction.',
      funFact: 'The region has more than 3,000 sandstone pillars.',
    },
    {
      id: 'okavango',
      name: 'Okavango Delta',
      x: 0.53,
      y: 0.66,
      description: 'A seasonal delta that floods the desert with lush waterways.',
      funFact: 'It is one of the world’s largest inland deltas.',
    },
    {
      id: 'banff',
      name: 'Banff National Park',
      x: 0.22,
      y: 0.24,
      description: 'Glacial lakes and alpine peaks form a pristine wilderness.',
      funFact: 'Canada’s first national park was established here.',
    },
    {
      id: 'patagonia',
      name: 'Patagonian Glaciers',
      x: 0.3,
      y: 0.86,
      description: 'Ice fields spill into turquoise lakes at the end of the world.',
      funFact: 'The region houses one of the largest ice caps outside Antarctica.',
    },
    {
      id: 'great-blue-hole',
      name: 'Great Blue Hole',
      x: 0.27,
      y: 0.5,
      description: 'A massive marine sinkhole ringed by vibrant coral walls.',
      funFact: 'It is a UNESCO World Heritage site in Belize.',
    },
  ],
};
