import type { GeoContent } from '../types';
import { WorldMap } from '../maps';

export const retroContent: GeoContent = {
  id: 'retro',
  name: 'Arcade Atlas',
  quest: 'Hunt down legendary arcade landmarks and gaming origins.',
  rounds: 10,
  mapBackground:
    'linear-gradient(180deg, rgba(5,5,5,1) 0%, rgba(10,10,10,1) 100%)',
  map: <WorldMap variant="retro" />,
  locations: [
    {
      id: 'silicon-valley',
      name: 'Silicon Valley (USA)',
      x: 0.18,
      y: 0.32,
      description: 'The birthplace of countless consoles and the heartbeat of gaming hardware innovation.',
      funFact: 'The first Atari offices were tucked into a humble Sunnyvale building.',
    },
    {
      id: 'atari-hq',
      name: 'Atari HQ (Sunnyvale)',
      x: 0.17,
      y: 0.34,
      description: 'A pilgrimage stop for arcade historians chasing the roots of the joystick era.',
      funFact: 'Atari popularized the arcade boom with Pong in the 1970s.',
    },
    {
      id: 'nintendo-kyoto',
      name: 'Nintendo HQ (Kyoto)',
      x: 0.81,
      y: 0.38,
      description: 'The iconic headquarters where classic franchises were forged.',
      funFact: 'Nintendo began as a playing card company in 1889.',
    },
    {
      id: 'tokyo-arcade',
      name: 'Tokyo Game District',
      x: 0.83,
      y: 0.34,
      description: 'Neon towers of cabinets, rhythm games, and competitive high-score battles.',
      funFact: 'Akihabara remains a global epicenter for arcade culture.',
    },
    {
      id: 'osaka-invaders',
      name: 'Space Invaders Origin (Osaka)',
      x: 0.82,
      y: 0.37,
      description: 'The launch pad for a pixelated invasion that took over the planet.',
      funFact: 'Space Invaders sparked a shortage of 100-yen coins in Japan.',
    },
    {
      id: 'seoul-pcbang',
      name: 'Seoul PC Bang',
      x: 0.83,
      y: 0.31,
      description: 'The competitive arena where esports culture exploded into the mainstream.',
      funFact: 'Korea’s PC bang culture helped define modern multiplayer gaming.',
    },
    {
      id: 'london-arcade',
      name: 'London Arcade Row',
      x: 0.44,
      y: 0.3,
      description: 'A retro alley lined with cabinets and cabinets-turned-time-machines.',
      funFact: 'Coin-op halls helped keep arcade culture alive in Europe.',
    },
    {
      id: 'paris-coinop',
      name: 'Paris Coin-Op Bar',
      x: 0.46,
      y: 0.32,
      description: 'A stylish stop where cocktail culture meets pixel-perfect competition.',
      funFact: 'Paris hosts annual retro-gaming festivals and tournaments.',
    },
    {
      id: 'moscow-tetris',
      name: 'Tetris Origin (Moscow)',
      x: 0.6,
      y: 0.28,
      description: 'The birthplace of the world’s most iconic falling-block puzzle.',
      funFact: 'Tetris was created on a Soviet-era computer in 1984.',
    },
    {
      id: 'espoo-nokia',
      name: 'Nokia HQ (Espoo)',
      x: 0.52,
      y: 0.22,
      description: 'Mobile gaming legends trace their roots back to this Finnish powerhouse.',
      funFact: 'Nokia’s Snake game reached over 350 million devices.',
    },
    {
      id: 'sao-paulo',
      name: 'São Paulo Arcade Hub',
      x: 0.32,
      y: 0.62,
      description: 'A vibrant arcade scene mixing rhythm games with classic cabinets.',
      funFact: 'Brazil’s arcade culture thrives in bustling city malls.',
    },
    {
      id: 'sydney-lan',
      name: 'Sydney LAN Lounge',
      x: 0.86,
      y: 0.76,
      description: 'Southern hemisphere LAN battles and retro tournaments all night long.',
      funFact: 'Australia hosts major retro-gaming expos each year.',
    },
  ],
};
